from __future__ import annotations

import re

ALLOWED_TOOL_ACTIONS: set[str] = {
    "volume_up",
    "volume_down",
    "mute_audio",
    "unmute_audio",
    "toggle_mute",
    "media_play_pause",
    "media_next",
    "media_previous",
    "take_screenshot",
    "find_file_by_name",
    "rename_file",
    "move_file",
    "copy_file",
    "delete_file",
    "create_folder",
    "extract_archive",
    "create_archive",
    "extract_text_docx",
    "extract_text_pdf",
    "summarize_document",
    "open_document",
    "search_docs_by_keyword",
    "search_filename",
    "search_file_content",
    "rebuild_index",
    "schedule_shutdown",
    "cancel_shutdown",
    "schedule_open_app",
    "open_app",
    "enable_startup",
    "disable_startup",
    "get_system_info",
    "get_local_ip",
    "get_public_ip",
    "check_internet",
    "ping_host",
    "restart_network_adapter",
    "create_txt",
    "create_docx",
    "create_markdown",
    "create_ps1",
    "create_email_template",
    "clean_downloads",
    "cancel_scheduled_task",
    "list_scheduled_tasks",
    "send_file_to_chat",
}

DANGEROUS_ACTIONS: set[str] = {
    "delete_file",
    "clean_downloads",
    "schedule_shutdown",
    "restart_network_adapter",
    "create_ps1",
    "enable_startup",
    "disable_startup",
    "copy_file",
    "move_file",
    "rename_file",
}

PATH_ACTION_ARGS: dict[str, list[str]] = {
    "rename_file": ["path"],
    "move_file": ["src", "dst"],
    "copy_file": ["src", "dst"],
    "delete_file": ["path"],
    "create_folder": ["path"],
    "extract_archive": ["path", "dst"],
    "create_archive": ["paths"],
    "extract_text_docx": ["path"],
    "extract_text_pdf": ["path"],
    "summarize_document": ["path"],
    "open_document": ["path"],
    "create_txt": ["filename"],
    "create_docx": ["filename"],
    "create_markdown": ["filename"],
    "create_ps1": ["filename"],
    "create_email_template": ["filename"],
    "send_file_to_chat": ["path"],
}

BLOCKED_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"\brm\s+-rf\b", re.IGNORECASE),
    re.compile(r"\bremove-item\b.+\b-recurse\b.+\b-force\b", re.IGNORECASE),
    re.compile(r"\bformat\b", re.IGNORECASE),
    re.compile(r"\breg\s+add\b|\breg\s+delete\b", re.IGNORECASE),
    re.compile(r"\bnet\s+user\b", re.IGNORECASE),
    re.compile(r"\bset-mppreference\b|\bdisable.*defender\b", re.IGNORECASE),
    re.compile(r"\bstart-bitstransfer\b|\binvoke-webrequest\b|\bcurl\b", re.IGNORECASE),
    re.compile(r"\bshutdown\s+/r\b", re.IGNORECASE),
    re.compile(r"\btaskkill\b.+/f\b.+/im\s+\*", re.IGNORECASE),
    re.compile(r"[;&|`]{1,2}"),
    re.compile(r"\$\(.+\)"),
]

BLOCKED_WINDOWS_PATH_PARTS = {
    "windows",
    "system32",
    "program files",
    "program files (x86)",
    "programdata",
    "appdata\\local\\temp\\..\\..\\windows",
}

SAFE_HOST_PATTERN = re.compile(r"^[A-Za-z0-9.-]{1,253}$")
